service: aws-node-express-dynamodb-api-project
frameworkVersion: "2 || 3"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: "20201221"
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:us-east-1:967900840755:table/Darwin1PostTable
        - arn:aws:dynamodb:us-east-1:967900840755:table/Darwin1UserTable
functions:
  hello:
    handler: src/handlers/handler.hello
    events:
      - http:
          path: /darwin
          method: GET
  login:
    handler: src/lambda/auth/login.handler
    events:
      - http:
          path: /auth
          method: POST
  register:
    handler: src/lambda/auth/register.handler
    events:
      - http:
          path: /auth/register
          method: POST
resources:
  Resources:
    Darwin1PostTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Darwin1PostTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
    Darwin1UserTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Darwin1UserTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
